### ISSUE TITLE
manager can't start

### ISSUE THREAD

**Issue by den-vasyliev** [banzaicloud/istio-operator#132]
**Describe the bug**

{"level":"error","ts":1552463370.8091638,"logger":"entrypoint","msg":"unable to run the manager","error":"open /tmp/cert/cert.pem: no such file or directory","stacktrace":"github.com/banzaicloud/istio-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/banzaicloud/istio-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/banzaicloud/istio-operator/cmd/manager/main.go:82\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:201"}

**Steps to reproduce the issue:**
fresh cluster - one master node:
git clone https://github.com/banzaicloud/istio-operator.git
cd istio-operator
make deploy

**Expected behavior**
Expect running istio-operator-controller-manager-0, but got:

NAME                                  READY   STATUS   RESTARTS   AGE
istio-operator-controller-manager-0   1/2     Error    1          22s

**kube-rbac-proxy logs**
k logs -n istio-system istio-operator-controller-manager-0 -c kube-rbac-proxy
I0313 07:46:13.956148       1 main.go:209] Generating self signed cert as no cert is provided
I0313 07:46:14.099652       1 main.go:242] Listening securely on 0.0.0.0:8443

**Comment by waynz0r** [comment]
Hi @den-vasyliev!

Thanks for reporting this!

We are preparing the master branch for the next release with Istio 1.1 support, there are some breaking changes, but the fix is coming shortly. You could use `release-1.0` branch until we fix this on `master`

**Comment by den-vasyliev** [comment]
appreciate for the fast feedback!
i'am going to present operator on "KIK" tech talk and try to launch release-1.0
thanks
