### ISSUE TITLE
Feature Request: Collaborate with Istio-Installer Project

### ISSUE THREAD

**Issue by StevenACoffman** [banzaicloud/istio-operator#150]
Please consider collaboration with the [istio-installer](https://github.com/istio-ecosystem/istio-installer) which has very similar goals for piece meal installation and upgrade of istio and it's dependencies, but has no aspirations towards other management.

Each component in the istio-installer is optional. Users can install the component defined in the new installer, use the equivalent component in istio-system, configured with the official installer, or use a different version or implementation.

For example you may use your own Prometheus and Graphana installs, or you may use a specialized/custom certificate provisioning tool, or use components that are centrally managed and running in a different cluster.

For our selfish use case, we would like to use the prometheus operator with istio and be able to upgrade and manage them separately. Ideally other pieces would similarly

**Comment by StevenACoffman** [comment]
istio-ecosystem/istio-installer#10

**Comment by matyix** [comment]
Hello @StevenACoffman - thanks for bringing this to our attention. Once this [PR is merged](https://github.com/banzaicloud/istio-operator/pull/144) that is opening the door to considering this integration. There are some overlaps (like this one - https://github.com/banzaicloud/istio-operator/pull/146) but the purpose of the operator is not just installing but managing the whole Istio lifecycle and enabling and automating more complex usage patterns like multi-cluster, CNI, etc.

**Comment by sdake** [comment]
@matyix as an FYI, the installer repository is a re-implementation of the existing Helm charts to decompose them.  These charts encode all of the wisdom (the whys things are done the way they are done).  An operator would then run against these templated manifests.  See my proposal here for how that work should proceed:

https://github.com/istio-ecosystem/istio-installer/issues/10#issuecomment-477914353

**Comment by martonsereg** [comment]
hi @sdake, we are already coordinating with the Istio Environments working group (cc / @ostromart), so we are aware of this proposal and would be happy to contribute to it and getting to an agreement that fits everybody's needs.

**Comment by Laci21** [comment]
The two projects went somewhat in different directions since then.
