### ISSUE TITLE
Istio injected envoy sidecar container sometimes fails to start with Istio 1.1.x

### ISSUE THREAD

**Issue by waynz0r** [banzaicloud/istio-operator#156]
There is an issue in Istio 1.1.x ([#9504](https://github.com/istio/istio/issues/9504)) which in some circumstances causes startup/readiness problem for the injected Envoy sidecar container.

We should check if it could be mitigated on our end!

**Comment by Laci21** [comment]
Solved in Istio 1.3, Istio 1.1 is EOL, see: https://github.com/istio/istio/issues/9504#issuecomment-532412566
