### ISSUE TITLE
Helm chart for deploying the Operator

### ISSUE THREAD

**Issue by devdattakulkarni** [banzaicloud/istio-operator#168]
**Is your feature request related to a problem? Please describe.**
Currently to install the Operator the suggested approach is to run the 'make deploy' command. I was wondering if it would be possible to create a Helm chart for the Operator. Users typically have Helm installed. Providing a Helm chart will make Operator installation consistent with other uses.

**Describe the solution you'd like to see**

The deploy rule from Makefile is below:
deploy: install-kustomize
	kubectl apply -f config/crds
	kubectl apply -f config/manager/namespace.yaml
	./scripts/image_patch.sh ./config/default/manager_image_patch.yaml ${IMG}
	bin/kustomize build $(KUSTOMIZE_BASE) | kubectl apply -f -

kustomize installation can be broken out into a separate script which installs all the pre-requisite tools. Such a script can also include the execution of image_patch.sh script and execution of 'kustomize build'. The rest of the commands that remain in the deploy rule are application of Kubernetes YAMLs. These can be turned into a Helm chart.

**Describe alternatives you've considered**
Alternative is what exists today - using the 'make deploy' command.

**Comment by martonsereg** [comment]
Hi, we already have a Helm chart for the operator, it can be found here: https://github.com/banzaicloud/banzai-charts/tree/master/istio-operator

**Comment by devdattakulkarni** [comment]
Awesome!! Thanks for the pointer.

May be I missed it, but I did not find reference to the chart in the README.

**Comment by martonsereg** [comment]
you're right, we forgot to mention it in the readme, we'll add it.
