### ISSUE TITLE
Istio 1.1.3

### ISSUE THREAD

**Issue by simongottschlag** [banzaicloud/istio-operator#170]
Hi!

You are always extremely fast with the support for the latest version of Istio. The latest version (1.1.3) is now released!

**Comment by simongottschlag** [comment]
@waynz0r I've tried your branch and it seems to be working!

**Comment by matyix** [comment]
Hey @simongottschlag - just FYI we released the [1.1.4 version](https://github.com/banzaicloud/istio-operator/pull/182) if you'd like to move from 1.1.3. As always, let us know how it works for you.
