### ISSUE TITLE
Datadog tracing

### ISSUE THREAD

**Issue by simongottschlag** [banzaicloud/istio-operator#171]
Hi!

Datadog is now supported with Istio 1.1.3. I’m not completely sure if it will be supported out of the box with the operator or if anything else is needed to supported?

I would love to be able to use it with the operator.

Thanks!

**Comment by matyix** [comment]
Hello @simongottschlag - once we release 1.1.3 (in the upcoming days) the Datadog integration will be enabled. Please get back to us and let us know how it works for you, after the finish the version bump.

**Comment by waynz0r** [comment]
@simongottschlag I've just created a PR for Istio 1.1.3 support, it is scheduled to be released early next week.

**Comment by simongottschlag** [comment]
@waynz0r would it be possible to get status.hostIP as the IP for datadog address? Making sure that we always go to the agent on the same host as the telemetry pod?

**Comment by blaketastic2** [comment]
How was the `$(HOST_IP):8126` value chosen? Can you point me to documentation that was used to set this as the sample yaml file?

**Comment by waynz0r** [comment]
@blaketastic2 afaik the Datadog agent usually runs on every host in the cluster. The sidecar container gets the host ip through the `HOST_IP` env variable, so it could connect to the dd agent on the host using `$(HOST_IP):8126` as the address by default.
