### ISSUE TITLE
Ability to set ports for Ingress Gateway

### ISSUE THREAD

**Issue by blaketastic2** [banzaicloud/istio-operator#190]
I'd like the ability to set ports for the ingress gateway. Currently, non-standard ports are not supported, as well as SSL termination by setting `targetPort: 80`

**Comment by martonsereg** [comment]
Hi @blaketastic2, we’ve added a config option in the CR to configure ports of the ingress gateway. See PR #191. The change is there in the latest version (0.1.12). Let us know if you need something else.
