### ISSUE TITLE
Significant performance degrade (ingress pods) with Istio 1.1

### ISSUE THREAD

**Issue by darwin67** [banzaicloud/istio-operator#193]
**Describe the bug**
Ingress latency for HTTPS increases dramatically that it will actually cause timeouts when trying to establish a TLS handshake with the ingress pods.

Once the TLS handshake has been established with the ingress pods, the process speed to the `VirtualService` and the actual `Service` are pretty fast.

**Steps to reproduce the issue:**
On a Kubernetes cluster in AWS (we create our cluster from `kubeadm` so not using EKS),

1. Install Istio through their officially supported Helm installation (v1.0.7)
2. Create a `Gateway` to attach to the generated ingress load balancer and update the DNS to point to the ELB
3. Create a cert as secret and attach to the `Gateway` created in `2` for TLS.
4. Deploy the sample [nginx deployment][nginx] in kubernetes docs with a `VirtualService`
5. Try running `curl -v https://<url-from-4>` a couple times or use something like [lolcat][lolcat] 

**Expected behavior**
Networking behavior shouldn't change including latency to the ingress pods regardless if it's TLS or not.

**Screenshots**
This is copied from an actual output when I was running `curl`. It takes like 5 ~ 10 seconds to even get the initial response from the `ingress` and it's slow enough that I can actually terminate the request before the handshake even starts.
```
❯ curl -v https://somewebsite.com/health
*   Trying 52.27.17.16...
* TCP_NODELAY set
* Connected to somewebsite.entelo.com (52.27.17.16) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
^C
```

**Additional context**
branch: `release-1.0`
istio: `v1.0.7`
kubernetes: `v1.14.1` not EKS
certs: generated from `Let's Encrypt` with `cert-manager`

We were trying to switch to the `1.0` Istio operator before doing an upgrade but this issue caused a cluster outage and we had to revert back to the Helm installation.
I tried digging around looking for the diffs between the Helm installation and the operator and there literally aren't much that seems to be different except for the `stdio` and `stdiotcp` rules the Operator adds to `Mixer`.

Our Istio installation and usage are fairly simple and the settings are very close to the default.

Also, reverting back to using the Helm installation immediately resolves all networking issues as well so there are definitely something going on when using the operator.

Trying a fresh install of Istio with the operator also seems to cause the same issues as well.

[nginx]: https://kubernetes.io/docs/tasks/run-application/run-stateless-application-deployment/
[lolcat]: https://github.com/jaseg/lolcat

**Comment by waynz0r** [comment]
@darwin67 thanks for reporting this, we are gonna look into it.

**Comment by matyix** [comment]
Thanks for reporting this @darwin67 - let us dig deep into the issue and get back with results or questions. Alternatively (for a faster resolution and exchange of configs, etc) could you join the istio-operator [Slack channel](https://slack.banzaicloud.io/)?

**Comment by waynz0r** [comment]
@darwin67 I tried to replicate the issue on fresh a PKE (v1.14.0) cluster on AWS, as you mentioned that you have seen the issue on a fresh install as well.

I could not replicate the issue with that setup so far.

You can find the applied resources here: https://gist.githubusercontent.com/waynz0r/e772cc8542c3c071ae0736be2b38002b/raw/90f1865e24e153bc7961dc21484ff872df2636dd/istio-nginx-sample.yaml

These are the detailed steps that I took:

```
# deploy the operator
release-1.0 ❯ make deploy
kubectl apply -f config/crds
customresourcedefinition.apiextensions.k8s.io/istios.istio.banzaicloud.io configured
customresourcedefinition.apiextensions.k8s.io/remoteistios.istio.banzaicloud.io configured
kubectl apply -f config/manager/namespace.yaml
namespace/istio-system created
./scripts/image_patch.sh ./config/default/manager_image_patch.yaml banzaicloud/istio-operator:0.0.11
bin/kustomize build config/default | kubectl apply -f -
clusterrole.rbac.authorization.k8s.io/istio-operator-manager-role unchanged
clusterrole.rbac.authorization.k8s.io/istio-operator-proxy-role unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-operator-manager-rolebinding configured
clusterrolebinding.rbac.authorization.k8s.io/istio-operator-proxy-rolebinding unchanged
service/istio-operator-controller-manager-metrics-service created
service/istio-operator-controller-manager-service created
statefulset.apps/istio-operator-controller-manager created

# apply the istio CR
release-1.0 ❯ kubectl apply -f config/samples/istio_v1beta1_istio.yaml
istio.istio.banzaicloud.io/istio-sample created

# check pods
release-1.0 u ❯ kubectl get pods
NAME                                     READY   STATUS    RESTARTS   AGE
istio-citadel-f54fd4659-2gt59            1/1     Running   0          54s
istio-egressgateway-655c7ccdf6-dk94l     1/1     Running   0          54s
istio-galley-f8d8974c8-l7b4p             1/1     Running   0          54s
istio-ingressgateway-bd574bcbf-qrwx9     1/1     Running   0          54s
istio-operator-controller-manager-0      2/2     Running   0          82s
istio-pilot-5cfcd7cd58-c7xz6             2/2     Running   0          54s
istio-policy-548fc68b44-srg82            2/2     Running   0          54s
istio-sidecar-injector-7fcd4f498-2d4s9   1/1     Running   0          46s
istio-telemetry-848ffc847f-kkls2         2/2     Running   0          54s

# check ingress gateway service
release-1.0 ❯ kubectl get svc/istio-ingressgateway
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP                                                               PORT(S)                                                                                                                   AGE
istio-ingressgateway   LoadBalancer   10.10.144.33   a6ac56cd175c611e996f4068bb227771-1891948989.eu-west-3.elb.amazonaws.com   80:31380/TCP,443:31390/TCP,31400:31400/TCP,15011:31410/TCP,8060:31420/TCP,853:31430/TCP,15030:31440/TCP,15031:31450/TCP   2m46s

# add self-singed cert for nginx.example.com
release-1.0 ❯ kubectl apply -f https://gist.githubusercontent.com/waynz0r/8c36d96c6e860913ef3804278c1cada8/raw/fd7474083f6cb77ab993a36751cdfdbbc7ef4208/nginx.example.com.yaml

# check and wait until it is actually available in the ingress gateway pod
release-1.0 ❯ kubectl exec -ti $(kubectl get pods --selector=app=istio-ingressgateway -o jsonpath='{.items[0].metadata.name}') cat /etc/istio/ingressgateway-certs/tls.crt
-----BEGIN CERTIFICATE-----
MIIDCzCCAfOgAwIBAgIJALwiEOpnKtZ1MA0GCSqGSIb3DQEBBQUAMBwxGjAYBgNV
....

# apply the sample resources
release-1.0 ❯ kubectl apply -f https://gist.githubusercontent.com/waynz0r/e772cc8542c3c071ae0736be2b38002b/raw/90f1865e24e153bc7961dc21484ff872df2636dd/istio-nginx-sample.yaml

# get ingress ip
release-1.0 ❯ INGRESS_IP=$(host $(kubectl get svc/istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].hostname}') | cut -d ' ' -f 4 | head -1)

release-1.0 u ❯ curl -vk --resolv nginx.example.com:443:${INGRESS_IP} https://nginx.example.com/
* Added nginx.example.com:443:35.181.47.16 to DNS cache
* Hostname nginx.example.com was found in DNS cache
*   Trying 35.181.47.16...
* TCP_NODELAY set
* Connected to nginx.example.com (35.181.47.16) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
...
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< server: envoy
< date: Mon, 13 May 2019 21:51:59 GMT
< content-type: text/html
< content-length: 612
< last-modified: Tue, 23 Dec 2014 16:25:09 GMT
< etag: "54999765-264"
< accept-ranges: bytes
< x-envoy-upstream-service-time: 0
<
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
...

# make some requests
release-1.0 ❯ for i in `seq 1 10`; time curl -sk --resolve nginx.example.com:443:${INGRESS_IP} https://nginx.example.com/ -o /dev/null
curl -sk --resolve nginx.example.com:443:${INGRESS_IP}  -o /dev/null  0.02s user 0.01s system 7% cpu 0.441 total
curl -sk --resolve nginx.example.com:443:${INGRESS_IP}  -o /dev/null  0.02s user 0.01s system 2% cpu 0.877 total
curl -sk --resolve nginx.example.com:443:${INGRESS_IP}  -o /dev/null  0.02s user 0.01s system 3% cpu 0.680 total
curl -sk --resolve nginx.example.com:443:${INGRESS_IP}  -o /dev/null  0.02s user 0.01s system 3% cpu 0.805 total
curl -sk --resolve nginx.example.com:443:${INGRESS_IP}  -o /dev/null  0.02s user 0.01s system 3% cpu 0.803 total
curl -sk --resolve nginx.example.com:443:${INGRESS_IP}  -o /dev/null  0.01s user 0.01s system 3% cpu 0.580 total
curl -sk --resolve nginx.example.com:443:${INGRESS_IP}  -o /dev/null  0.02s user 0.01s system 8% cpu 0.248 total
curl -sk --resolve nginx.example.com:443:${INGRESS_IP}  -o /dev/null  0.02s user 0.01s system 9% cpu 0.256 total
curl -sk --resolve nginx.example.com:443:${INGRESS_IP}  -o /dev/null  0.02s user 0.01s system 9% cpu 0.256 total
curl -sk --resolve nginx.example.com:443:${INGRESS_IP}  -o /dev/null  0.02s user 0.01s system 10% cpu 0.266 total

# cleanup
release-1.0 ❯ kubectl delete namespace demo
release-1.0 ❯ kubectl -n istio-system delete istios/istio-sample
release-1.0 ❯ kubectl delete namespace istio-system
```

**Comment by darwin67** [comment]
Hi @waynz0r 

Thanks for looking into this. The issue didn't pop up immediately and seems to happen gradually over time.
It happened to my cluster (fresh install) after running for a couple days and I was seeing the operator restarting like 200 times.

As from transiting from Helm, it was immediate.

I wonder if this could only happen when there's a certain amount of load on the cluster? :thinking:

**Comment by darwin67** [comment]
If you think you can't replicate it, please feel free to close this issue since I understand it can be very tricky to reproduce.

I don't know all the variables to trigger this behavior so it'll be great that you could just keep this in mind and maybe investigate deeper when a similar report shows up.

As for now, we're moving back to use Helm and maybe wait for [this][official] to be ready.

[official]: https://github.com/istio/operator

**Comment by matyix** [comment]
Hello @darwin67 - any chance that we can check that cluster where you've seen this issue (or we can give you a cluster and let you deploy your stuff - happy to sign an NDA or whatever it needs to debug this). We run quite a few Istio clusters and have not seen this, nor able to reproduce - however if there is any chance we'd like to have your issue (even if might be an edge case) fixed. 

About the operator you linked - we are involved and part of [that team](https://github.com/istio/operator/blob/master/CODEOWNERS), thus I'd like to understand your issue either way as fundamentally there will be no significant differences between this and that operator, other than [this](https://github.com/banzaicloud/istio-operator/pull/144).

**Comment by waynz0r** [comment]
@darwin67 the operator restart sounds strange and also it should not have affected pilot or mixer if there was no change in the CR regarding those components.

Do you have by any chance logs from the operator pod?

**Comment by darwin67** [comment]
@matyix @waynz0r 
Hey, so here's an update. I think you can disregard this since it looks like an upstream issue with Istio itself.

https://github.com/istio/istio/issues/13578
https://github.com/istio/istio/issues/13863
https://github.com/istio/istio/issues/12755

**Comment by darwin67** [comment]
FYI:

I did an upgrade with Helm this time and I'm seeing the exact same issue.
Here's a screenshot of what it looks like.

This happens on requests that doesn't have caches, so incognito and `curl` will definitely be impacted.

![ingress](https://user-images.githubusercontent.com/5746693/57739286-d7752b00-7667-11e9-8ade-3dfacda2a022.png)

**Comment by darwin67** [comment]
> @darwin67 the operator restart sounds strange and also it should not have affected pilot or mixer if there was no change in the CR regarding those components.
> 
> Do you have by any chance logs from the operator pod?

The pod became accessible so I wasn't able to retrieve any logs from it. :(

**Comment by darwin67** [comment]
Hey @waynz0r @matyix , after spending some more time tweaking around, looks like there something interesting going on with the `istio-ingressgateway` deployment itself.

The interesting part is there aren't any logs or signals that stands out and I only spot the performance difference when changing the number of pods running.

I've created an issue on Istio https://github.com/istio/istio/issues/14102 reporting a bit of my findings, so I'm going to close this issue now.
Thanks for the swift response guys. :)

**Comment by darwin67** [comment]
Hey @waynz0r @matyix 

Not sure if you have been following the issue on Istio, but do you think you could reproduce it with the additional info I've provided there?

I'm kind of surprised that no one else is reporting on it so far so I'm suspecting there's something with my cluster setup, but then it's created with `kubeadm` so it's 100% compliant to the k8s standards...

**Comment by matyix** [comment]
Hey @darwin67 - we will certainly try, as you provided lots of new information in [istio/https://github.com/istio/istio/issues/14102]. 

We'd be also happy to check your cluster or let you create a fresh one within our environment to debug it properly. By any chance are you (or someone from your organization) at KubeCon next week - we might do a debug session there together, otherwise let's talk on Slack see how can we reproduce this?

**Comment by darwin67** [comment]
Unfortunately, we won't be at KubeCon next week. I've joined the Slack channel so I'll ping you. :)

**Comment by varsraja** [comment]
Iam using istio 1.1.8  with kube 1.14 and hitting the same issue with a tls SIMPLE mode. The gateway just hangs at client hello  . While the non -https port work fine.
