### ISSUE TITLE
Add support for nodeSelector

### ISSUE THREAD

**Issue by simongottschlag** [banzaicloud/istio-operator#200]
Hi,

I took a look but it seems like it’s not possible to use nodeSelector with for example ingress gateway.

Would it be possible to add support for it?

Thanks!

**Comment by martonsereg** [comment]
Hi Simon,

we've added configurable `affinities`, `nodeSelectors` and `tolerations` in #201 
I've just kicked off a new release (0.1.13), docker images should be available once docker hub builds it.

**Comment by simongottschlag** [comment]
> Hi Simon,
> 
> we've added configurable `affinities`, `nodeSelectors` and `tolerations` in #201
> I've just kicked off a new release (0.1.13), docker images should be available once docker hub builds it.

Blazing fast! I'll try it out as soon as possible.
