### ISSUE TITLE
Please provide delete steps

### ISSUE THREAD

**Issue by mossuchida** [banzaicloud/istio-operator#208]
Currently, there is no documentation or steps for deleting CRs (ISTIO components) & operator itself. Usually, we can run kubectl delete -f <cr yaml file or operator yaml file>, but the steps are not clear.
Please provide steps to delete completely.

**Comment by Laci21** [comment]
Hi @mossuchida, we've added the necessary steps to the [README.md](https://github.com/banzaicloud/istio-operator/blob/release-1.1/README.md#uninstall).

Thank you for your suggestion!
