### ISSUE TITLE
Corrupting CoreDNS ConfigMap on reconsolidating istiocoredns component

### ISSUE THREAD

**Issue by mousavian** [banzaicloud/istio-operator#226]
**Describe the bug**
Upon creating new `istio.istio.banzaicloud.io` resource, when `istiocoredns` component is not enabled, `istiocoredns` still gets reconsolidated and causing corrupt coredns ConfigMap with wrong proxy (missing destination): 
```
global:53 {
  errors
  cache 30
  proxy .
}
```

And after few seconds, when coredns pods are reloaded due to config change, they will throw error and stuck in `CrashLoopBackOff` state:
```
$ kubectl log -n kube-system coredns-76b76ccc9-zs8cv
plugin/proxy: /etc/coredns/Corefile:20 - Error during parsing: Wrong argument count or unexpected line ending after '.'
```

This is due to having empty `clusterIP` when `desiredState != k8sutil.DesiredStatePresent`
https://github.com/banzaicloud/istio-operator/blob/ae4867d279/pkg/resources/istiocoredns/coredns.go#L52-L73

**Steps to reproduce the issue:**
`kubectl apply -f config/samples/istio_v1beta1_istio_minimal.yaml`

**Expected behavior**
If I'm not mistaken, `istiocoredns` reconsolidation should only happen when `istiocoredns` is enabled.

**Comment by Laci21** [comment]
@mousavian, thank you very much for reporting this issue, at first glance, I think you are totally right the ConfigMap should only be reconciled when `istiocoredns` is enabled. We'll take a look, create a PR and release a new version with the fix today.
