### ISSUE TITLE
request new feature: configure PodSecurityPolicy in Istio CR

### ISSUE THREAD

**Issue by JoshuaAndrew** [banzaicloud/istio-operator#233]
**Is your feature request related to a problem? Please describe.**

if  I enable podsecuritypolicy in kube-apiserver, you would find the problem below, there is no 
available pod running, so we should add some configuration in Istio CRD to configure podsecuritypolicy name.
```
[root@k8s-master-1 istio]# kubectl get deploy -nistio-system
NAME                     DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
istio-citadel            1         0         0            0           6m35s
istio-egressgateway      1         0         0            0           6m33s
istio-galley             1         0         0            0           6m35s
istio-ingressgateway     1         0         0            0           6m34s
istio-pilot              1         0         0            0           6m34s
istio-policy             1         0         0            0           6m32s
istio-sidecar-injector   1         0         0            0           6m22s
istio-telemetry          1         0         0            0           6m32s
```

**Comment by waynz0r** [comment]
Hi @JoshuaAndrew,

Thank you for your suggestion!

We are gonna look into it and figure out an easy way to configure PSP in the CR for the Istio components.

**Comment by JoshuaAndrew** [comment]
@waynz0r    wonderful !

**Comment by JoshuaAndrew** [comment]
@waynz0r  Is there any progress?

**Comment by waynz0r** [comment]
Hi @JoshuaAndrew,

we had several internal discussions about how to solve this problem. We think it is out of scope of the operator itself to specify and set pod security policies. 

We are going to add a basic PSP to the helm chart and to the kustomize flow to support PSP enabled clusters.

**Comment by waynz0r** [comment]
Hi @JoshuaAndrew,

we just released a new helm chart version (0.0.14). You can use `rbac.psp.enabled=true` to enable psp   resource deployment for the operator and the Istio components.

Please let us know how it works for you!

**Comment by JoshuaAndrew** [comment]
@waynz0r  Nice cool !

**Comment by Morriz** [comment]
well, thanks for attempt #1, but it is fully permissive...not recommended:
```
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - configMap
  - emptyDir
```

I suggest creating more finegrained psps for the components. Which components need access to what?

**Comment by waynz0r** [comment]
@Morriz,

the *example* PSP was added into the repo merely to allow running the Istio components on a cluster where PSP is enabled.

Fine tuning largely depends on the actual configuration of the Istio components and as such usually happens on a per-user basis.

Most of the Istio operator users use their own custom PSP for each component based on their own requirements; like us, we give a custom PSP to our customers based on their usage patterns.

**Comment by Morriz** [comment]
I get it, but it might be nice to offer it just right for the components that are in the chart, just like the chart guidelines say. And thenlet the users figure it out for their userland workloads...maybe provide a link to a default "restricted" psp that is good for workloads for tenants
