### ISSUE TITLE
Namespaces listed in "autoInjectionNamespaces" inconsistent with actual namespace labels

### ISSUE THREAD

**Issue by Laci21** [banzaicloud/istio-operator#243]
**Describe the bug**

I encountered a situation when I had a `test` namespace which was listed in the [autoInjectionNamespaces](https://github.com/banzaicloud/istio-operator/blob/release-1.1/config/samples/istio_v1beta1_istio.yaml#L12) list of the Istio Custom Resource, but the necessary labels (`istio-injection=enabled,istio-operator-managed-injection=enabled`) were not present on the `test` namespace itself which should have been the case.

**Steps to reproduce the issue:**
Please describe the steps to reproduce the issue.

1. At first, I had a `test` namespace which was listed in the `autoInjectionNamespaces` list of the Istio CR and the necessary labels (`istio-injection=enabled,istio-operator-managed-injection=enabled`) were present on the `test` namespace.
2. I deleted the `test` namespace
3. I recreated the `test` namespace

**Expected behavior**

I consider two possible solutions:

- When the `test` namespace is deleted, it could also be removed from the `autoInjectionNamespaces` list of the Istio CR. In this case, when the namespace is recreated, the user has to modify the Istio CR to include the `test` namespace in the `autoInjectionNamespaces` list if they want to enable automatic sidecar injection on that namespace. This would mean an additional manual step for the user, but we could be sure that this is what the user wants (see the other possibility).
- When the `test` namespace is deleted, it stays in the `autoInjectionNamespaces` list of the Istio CR. When it is recreated, an automatic reconciliation happens and the labels are attached to the newly created namespace. This solution would be more convenient to the user as it happens automatically, but could lead to issues if it is not actually the user's intention to enable automatic sidecar injection on that newly created namespace.

I might lean towards the first approach. Even though it involves a manual step, this way we can be sure this is what the user wants and could avoid issues when the user don't want to enable automatic sidecar injection on that namespace. However, I'm not sure that the operator modifying it's own CR would be a good idea that's why the second approach might be better yet.

**Comment by Morriz** [comment]
I favor option 1, as after deleting a namespace k8s should not hold any references to it anymore...

any updates here?

**Comment by Laci21** [comment]
Hi @Morriz,

Thanks for sharing your opinion!

Unfortunately, we haven't dealt with this yet, but we are happy to accept PRs. Otherwise, you'll be able to follow the progress of this issue here.

**Comment by Laci21** [comment]
For further reference:
Solved with the second listed possible solution which is:
When the `test` namespace is deleted, it stays in the `autoInjectionNamespaces` list of the Istio CR. When it is recreated, an automatic reconciliation happens and the labels are attached to the newly created namespace.
