### ISSUE TITLE
Some Kustomize resources use a namespace of `system` rather than `istio-system`

### ISSUE THREAD

**Issue by 06kellyjac** [banzaicloud/istio-operator#261]
**Describe the bug**

Some Kustomize resources use a namespace of `system` rather than `istio-system`. This seems like they should either go in `istio-system` or if it should go in a different namespace it should be something more distinct than `system` such as `istio-operator` or `istio-operator-system`

https://github.com/banzaicloud/istio-operator/blob/release-1.2/config/base/manager/manager.yaml#L5
https://github.com/banzaicloud/istio-operator/blob/release-1.2/config/base/manager/manager.yaml#L20

https://github.com/banzaicloud/istio-operator/blob/release-1.2/config/base/rbac/rbac_role_binding.yaml#L13

**Steps to reproduce the issue:**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Laci21** [comment]
Further reference for passers-by:
The recommended usage options are documented here: https://github.com/banzaicloud/istio-operator/blob/release-1.2/config/README.md
