### ISSUE TITLE
question: reconciliation error for ingress

### ISSUE THREAD

**Issue by dad264** [banzaicloud/istio-operator#266]
I'm getting reconciliation errors with the following message: 
`istio-operator-operator-0 manager {"level":"info","ts":1564156132.4932094,"logger":"controller","msg":"invalid ingress status"}`

I'm currently setting our ingress-gateway to type "nodeport", so am I correct in assuming there wouldn't be a `service.Status.LoadBalancer.Ingress`  status to pull in https://github.com/banzaicloud/istio-operator/blob/0.1.22/pkg/controller/istio/istio_controller.go#L324 ?

Hoping my installation is "healthy" other than that. (The rest of the logs look ok).

thanks!

**Comment by waynz0r** [comment]
Hi @dad264,

that is certainly an issue, thanks for reporting this! A fix will be released early next week.

You can try a custom build from https://github.com/banzaicloud/istio-operator/tree/ingress-endpoints-fix until then.

**Comment by Laci21** [comment]
Hi @dad264,

There are new images built for Istio 1.1 (`0.1.23`) and Istio 1.2 (`0.2.2`) with the fix.

Thanks for reporting the issue!

**Comment by dad264** [comment]
@Laci21 Looks good! Thanks!
