### ISSUE TITLE
deployment on  chart@0.0.15 fails with: spec.version in body is required

### ISSUE THREAD

**Issue by Morriz** [banzaicloud/istio-operator#277]
Is that documented somewhere? I want to update the manifest, but how?

**Comment by waynz0r** [comment]
Hi @Morriz,

the `version` must be specified in the CR you want to apply.

Like in this sample, https://github.com/banzaicloud/istio-operator/blob/72b4767bf411441b6b305f5a0c7470438de40dd7/config/samples/istio_v1beta1_istio.yaml#L8

**Comment by Morriz** [comment]
Yeah, it's documented in the CRD. I should read first...tnx
