### ISSUE TITLE
Installing adaptors with Operator

### ISSUE THREAD

**Issue by psandhu79** [banzaicloud/istio-operator#284]
Its not clear to me how to install an adaptor with the Istio operator, I would like to install the Stackdriver adaptor

**Comment by waynz0r** [comment]
Hi @psandhu79,

it should be as simple as applying the stackdriver adapter resources (https://raw.githubusercontent.com/istio/istio/master/mixer/adapter/stackdriver/operatorconfig/stackdriver.yaml) after you set project id and credentials.

The API key option is probably the simplest option for credentials.

You can also store a service account JSON in a secret called `policy-adapter-secret` in the namespace where mixer is installed, usually its `istio-system`, the contents of it gets mounted into the `/var/run/secrets/istio.io/policy/adapter` directory, so the `serviceAccountPath` setting in the stackdriver adapter should be something like `/var/run/secrets/istio.io/policy/adapter/service-account.json`.

I never tried it to be honest, but it should work. I'll look into it tomorrow!

**Comment by psandhu79** [comment]
@waynz0r thank you I tried that after posting this question however question about the CRDs that come with Istio not all these are installed. There is a Stackdriver crd which I believe needs to be run before applying the Stackdriver.yaml.

So question should the operator and crd in the install also install all the crds

**Comment by waynz0r** [comment]
@psandhu79 which istio version do you use?

There were some CRD related changes in Istio 1.2 (https://discuss.istio.io/t/deprecation-notice-custom-mixer-adapter-crds/2055), so the stackdriver resources at that url is not compatible with it. You have to use `instance` CRs instead of specific CRs like `metrics`, `stackdriver`, and so on..
