### ISSUE TITLE
Support separate config for telemetry and policy 

### ISSUE THREAD

**Issue by mousavian** [banzaicloud/istio-operator#295]
**Is your feature request related to a problem? Please describe.**
Currently telemetry (deploy & hpa) and policy are sharing the same config for mixer container and hpa.
We have observed that they are behaving differently and require custom resource and hpa configuration. 
This has been addressed in Helm installation in istio repository ([1](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml#L92-L98), [2](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml#L283-L289)) but would be great to have it here as well. 

**Describe the solution you'd like to see**
To have resources and hpa configuration options in telemetry and policy config

**Describe alternatives you've considered**

**Additional context**

**Comment by Laci21** [comment]
Hi @mousavian,

I agree it would be nice to configure these deployments separately.

I can only repeat myself for this as well, in the next 2-3 weeks we have limited capacity, so we cannot promise anything. PRs are always welcome, otherwise, we will try to do our best to resolve this as soon as we can.

**Comment by matyix** [comment]
@mousavian you can track the progress of the [Separate policy and telemetry configuration](https://github.com/banzaicloud/istio-operator/pull/297/) here - there has been some work done over the weekend) #297

**Comment by mousavian** [comment]
Thanks guys for following up with this, 
I have overutilized the resources for mixer to cover both deployments needs, on my last week at iflix.
So there shouldn't be too much rush for this but would be good to have.

_Maybe_ someone from iflix will follow up with this in future.
Cheers,

**Comment by waynz0r** [comment]
@mousavian,

this feature just got released with latest operator version.

**Comment by mousavian** [comment]
Cc @olga-mir @visualdensity @ronny
