### ISSUE TITLE
[EPIC] Istio 1.1 support

### ISSUE THREAD

**Issue by matyix** [banzaicloud/istio-operator#30]
Add support for Istio master (1.1) instead of 1.0.5 only

**Comment by rshriram** [comment]
what is involved in updating the code to do this?

**Comment by waynz0r** [comment]
@rshriram  Our main priority was to provide support for Istio 1.0.x first. We were just started working on Istio v1.x support, how big change will that need on the current codebase is not yet clear.

It would be great if you can help us to bring this feature out asap!

We have a dedicated channel on our slack, if you like to join to the conversation https://slack.banzaicloud.io #istio-operator
