### ISSUE TITLE
mTLS migration and policy definition

### ISSUE THREAD

**Issue by mc1711** [banzaicloud/istio-operator#310]
We are using istio-operator and we are currently migrating a project to use mTLS. 

We do not enable mTLS on all our pods so we need to manually create a policy to set mTLS permissive mode for all the services talking to the no-mtls pods. 

To do that we manually create a policy like this 

apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "migration-policy"
spec:
  targets:
  - name: svc1
  - name: svc2
  - mtls:
      mode: PERMISSIVE 

Is there a way to create a policy like the one described above using the operator? 
If not, could this be a feature that you would consider to add?

Thanks in advance and sorry if this is not the right place to ask this question

**Comment by Laci21** [comment]
Hi @mc1711,

It's great to hear that you use the operator!

Honestly, it feels like this feature is out of scope of the operator, but it is definitely something that we would consider adding to our [Backyards](https://banzaicloud.com/blog/istio-the-easy-way/) product.

It is not on our short term roadmap right now, but we will let you know as soon as we have a feature which can help you achieve what you described.

Until then, I would recommend you to follow our [community Slack channel](https://slack.banzaicloud.io/), specifically the `#istio-operator` and `#backyards` channels.

**Comment by mc1711** [comment]
Thanks a lot @Laci21 .. I will follow the istio-operator and backyards project.

**Comment by Laci21** [comment]
Hi @mc1711,

As I mentioned earlier, we hadn't planned to add this feature to the operator rather we wanted to add it to [Backyards](https://banzaicloud.com/docs/backyards), which we did in [Backyards 1.1](https://banzaicloud.com/blog/backyards-release-1-1/).

In Backyards, you don't need to manually create the aformentioned `Policy` resources, you can achieve the same result by using the Backyards UI or CLI tool. You can read more about the details in our [blog post](https://banzaicloud.com/blog/istio-mtls/) or in the [docs](https://banzaicloud.com/docs/backyards/features/mtls-settings/).

The instructions are documented how easily you can [try out Backyards](https://banzaicloud.com/docs/backyards/quickstart) and [this feature](https://banzaicloud.com/docs/backyards/features/mtls-settings/), let us know what you think of it!
