### ISSUE TITLE
Running Envoy proxy through CRI 

### ISSUE THREAD

**Issue by truongnh1992** [banzaicloud/istio-operator#316]
**Is your feature request related to a problem? Please describe.**
When upgrading Istio sidecar (Envoy proxy):
In order to change the sidecar container, the pod needs to be restarted, so the application container will be restarted as well => it will cause downtime for that specific pod.

**Describe the solution you'd like to see**
In order to change the sidecar container without restaring the pod ⇒ **We have to run the sidecar out of pod (community has idea that running Envoy through CRI. Unfortunately, there isn’t any formal proposal yet)** and Envoy supports hot restart meaning you start a new Envoy binary (could be different version) and traffic is shifted to the new Envoy without traffic loss [1]

[1] https://blog.envoyproxy.io/envoy-hot-restart-1d16b14555b5

**Comment by Laci21** [comment]
This effort has been discontinued, AFAIK.
