### ISSUE TITLE
Operator never leaves Reconciling status

### ISSUE THREAD

**Issue by res0nat0r** [banzaicloud/istio-operator#328]
**Describe the bug**

The operator never leaves `Reconciling` status, thus never becomes ready.

**Steps to reproduce the issue:**

```bash
git checkout istio-1.3.4
make deploy
kubectl apply -n istio-system -f custom-istio-operator.yml
```

**Expected behavior**

The operator should become ready and usable.

**Screenshots**

```
$ kubectl get all -n istio-system
NAME                                      READY   STATUS    RESTARTS   AGE
pod/istio-operator-controller-manager-0   2/2     Running   3          66m

NAME                                                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/istio-operator-controller-manager-metrics-service   ClusterIP   172.20.184.254   <none>        8443/TCP   66m
service/istio-operator-controller-manager-service           ClusterIP   172.20.173.207   <none>        443/TCP    66m
service/istio-operator-webhook                              ClusterIP   172.20.9.32      <none>        443/TCP    66m

NAME                                                 READY   AGE
statefulset.apps/istio-operator-controller-manager   1/1     66m
```

```
$ kubectl get istios -n istio-system
NAME                        STATUS        ERROR   GATEWAYS     AGE
istio-shared-tools   Reconciling           <no value>   42m
```

**Additional context**

This install process works fine for me on a smaller k8s cluster I'm testing against. I'm installing via the `istio-1.3.4` branch. I *think* this is related to the size of the cluster. I think the default settings for the operator aren't large enough for it to index/reconcile everything running and become ready. This cluster has a couple hundred pods running. 

I remember in the past on older releases of the operator I manually edited the istios/operator-name and modified the memory settings manually and the operator became ready after that.

This release I see a handful of pods with cpu/memory settings, I've bumped all of them but this doesn't fix this issue. I'm not sure exactly the root cause but I suspect it is not enough RAM in the default settings for the operator to initialize / index what it needs on large clusters. I can supply any additional debug info if needed, please let me know.

**Comment by waynz0r** [comment]
Hi @res0nat0r,

can you please paste some logs from the operator container in `pod/istio-operator-controller-manager-0`?

**Comment by Laci21** [comment]
Hi @res0nat0r,

First of all, for more robust builds, I would recommend you to use the `release-1.x` branches (`release-1.3` in your case if you want Istio 1.3, or switch to `release-1.4` for Istio 1.4 if you wish). This shouldn't have caused the issue you've experienced but you can usually expect more stable builds on the `release-1.x` branches.

We can see that your operator pod was restarted three times, so as @waynz0r mentioned it would help to see the logs of the operator to see what's going on there: `kubectl logs -n istio-system istio-operator-controller-manager-0 manager`

There is this [defaultResources](https://github.com/banzaicloud/istio-operator/blob/release-1.4/config/samples/istio_v1beta1_istio.yaml#L16) field which can be set in the Custom Resource. For all control plane components these resources will be used by default, but they can be overriden for each control plane components (e.g. for Pilot: https://github.com/banzaicloud/istio-operator/blob/release-1.4/config/samples/istio_v1beta1_istio.yaml#L28).

**Comment by res0nat0r** [comment]
Hi @Laci21 / @waynz0r 

- So I was wanting to use a point release branch so we can always point to a specific istio release that will never change, hence why I picked `istio-1.3.4`. If I use `release-1.3`, this could be release `1.3.4` today, and possibly `1.3.5` next month no? We're trying to pin to an exact release we know works across the board so hence the reason I was using an explicit release branch name.

Also it looks like from the logs, is just this repeating over and over, since the istio operator is just stuck in `Reconciling`.

```
istio-operator-controller-manager-0 manager {"level":"info","ts":1574108391.0517251,"logger":"controller","msg":"cannot trigger reconcile while already reconciling","trigger":"istio-system/istio-shared-tools","correlationID":"52a6d800-d235-4dcf-8534-ec9ffd0d6440"}
istio-operator-controller-manager-0 manager {"level":"info","ts":1574108421.0520806,"logger":"controller","msg":"Reconciling Istio","trigger":"istio-system/istio-shared-tools","correlationID":"43f277b1-075c-4d63-bda9-170b39b4476d"}
istio-operator-controller-manager-0 manager {"level":"info","ts":1574108421.0521762,"logger":"controller","msg":"cannot trigger reconcile while already reconciling","trigger":"istio-system/istio-shared-tools","correlationID":"43f277b1-075c-4d63-bda9-170b39b4476d"}
istio-operator-controller-manager-0 manager {"level":"info","ts":1574108451.0524242,"logger":"controller","msg":"Reconciling Istio","trigger":"istio-system/istio-shared-tools","correlationID":"d2d06244-fe2f-490e-a4b0-b8d4ca2d2b4f"}
istio-operator-controller-manager-0 manager {"level":"info","ts":1574108451.0524848,"logger":"controller","msg":"cannot trigger reconcile while already reconciling","trigger":"istio-system/istio-shared-tools","correlationID":"d2d06244-fe2f-490e-a4b0-b8d4ca2d2b4f"}
istio-operator-controller-manager-0 manager {"level":"info","ts":1574108481.052792,"logger":"controller","msg":"Reconciling Istio","trigger":"istio-system/istio-shared-tools","correlationID":"154c61a8-6834-4edd-b458-16de0499bee2"}
istio-operator-controller-manager-0 manager {"level":"info","ts":1574108481.0528524,"logger":"controller","msg":"cannot trigger reconcile while already reconciling","trigger":"istio-system/istio-shared-tools","correlationID":"154c61a8-6834-4edd-b458-16de0499bee2"}
```

Thanks, let me know if you need anything else.

**Comment by Laci21** [comment]
Hi @res0nat0r,

If you want a specific version you can always use a concrete [release](https://github.com/banzaicloud/istio-operator/releases). For that, you can checkout to that tag and deploy from there.

Isn't there any relevant looking info in the logs before this `Reconciling` status is stuck? We can move this conversation to our [istio-operator community slack](https://community-banzaicloud.slack.com/archives/CGKQF5HUP) channel if you wish and maybe we can help you debug your issue faster.

Otherwise, you could try restarting the operator pod, but before that I would save the full logs of it to be able to understand what happened.

**Comment by res0nat0r** [comment]
Hi @Laci21,

Ah that makes sense, I can use the `release-1.x` branch and just pin the specific version in my yml.

This is what I see from the beginning of the pod logs before the repeating reconciling messages:

```
{"level":"info","ts":1573772287.2501516,"logger":"entrypoint","msg":"setting up client for manager"}
{"level":"info","ts":1573772287.250557,"logger":"entrypoint","msg":"watch all namespaces"}
{"level":"info","ts":1573772287.2505877,"logger":"entrypoint","msg":"setting up manager"}
{"level":"info","ts":1573772288.0464447,"logger":"entrypoint","msg":"Registering Components."}
{"level":"info","ts":1573772288.0464969,"logger":"entrypoint","msg":"setting up scheme"}
{"level":"info","ts":1573772288.04684,"logger":"entrypoint","msg":"Setting up controller"}
{"level":"info","ts":1573772288.0470605,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"config-controller","source":"kind source: istio.banzaicloud.io/v1beta1, Kind=Istio"}
{"level":"info","ts":1573772288.047225,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"config-controller","source":"kind source: istio.banzaicloud.io/v1beta1, Kind=RemoteIstio"}
{"level":"info","ts":1573772288.0473466,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"config-controller","source":"kind source: /v1, Kind=Service"}
{"level":"info","ts":1573772288.047514,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"remoteconfig-controller","source":"kind source: istio.banzaicloud.io/v1beta1, Kind=RemoteIstio"}
{"level":"info","ts":1573772288.0475523,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"remoteconfig-controller","source":"kind source: istio.banzaicloud.io/v1beta1, Kind=Istio"}
{"level":"info","ts":1573772288.0475788,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"remoteconfig-controller","source":"kind source: /v1, Kind=Pod"}
{"level":"info","ts":1573772288.0476918,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"remoteconfig-controller","source":"kind source: /v1, Kind=service"}
{"level":"info","ts":1573772288.0477252,"logger":"entrypoint","msg":"setting up webhooks"}
{"level":"info","ts":1573772288.0478292,"logger":"webhook-server","msg":"started"}
{"level":"info","ts":1573772288.047855,"logger":"entrypoint","msg":"Starting the Cmd."}
{"level":"info","ts":1573772289.5482771,"logger":"kubebuilder.webhook","msg":"installing webhook configuration in cluster"}
{"level":"info","ts":1573772289.5484781,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"remoteconfig-controller"}
{"level":"info","ts":1573772289.5484514,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"config-controller"}
{"level":"info","ts":1573772289.6487563,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"remoteconfig-controller","worker count":1}
{"level":"info","ts":1573772289.7448087,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"config-controller","worker count":1}
{"level":"info","ts":1573772289.745004,"logger":"controller","msg":"Reconciling Istio","trigger":"istio-system/istio-shared-tools","correlationID":"fcbfa566-2214-49c0-b44e-c96df0ff8de3"}
{"level":"info","ts":1573772289.74505,"logger":"controller","msg":"cannot trigger reconcile while already reconciling","trigger":"istio-system/istio-shared-tools","correlationID":"fcbfa566-2214-49c0-b44e-c96df0ff8de3"}
{"level":"info","ts":1573772295.5490806,"logger":"kubebuilder.admission.cert.writer","msg":"cert directory doesn't exist, creating","directory":"/tmp/cert"}
{"level":"info","ts":1573772319.745378,"logger":"controller","msg":"Reconciling Istio","trigger":"istio-system/istio-shared-tools","correlationID":"8984385e-df83-4d2b-9d9c-27924d59d971"}
{"level":"info","ts":1573772319.745471,"logger":"controller","msg":"cannot trigger reconcile while already reconciling","trigger":"istio-system/istio-shared-tools","correlationID":"8984385e-df83-4d2b-9d9c-27924d59d971"}
{"level":"info","ts":1573772349.7457182,"logger":"controller","msg":"Reconciling Istio","trigger":"istio-system/istio-shared-tools","correlationID":"2520a3c7-2635-4e1b-937c-481c1dee0428"}
{"level":"info","ts":1573772349.74578,"logger":"controller","msg":"cannot trigger reconcile while already reconciling","trigger":"istio-system/istio-shared-tools","correlationID":"2520a3c7-2635-4e1b-937c-481c1dee0428"}
```

I'm happy to join the Slack org and help debug further, the link above isn't allowing me to create a guest account and sign in, do I need an invite link?

Thanks.

**Comment by Laci21** [comment]
Sorry, this is where you can join our Slack: https://slack.banzaicloud.io/

**Comment by res0nat0r** [comment]
Thanks! I'll sign in in a bit.

**Comment by Laci21** [comment]
@res0nat0r, the [0.4.2](https://github.com/banzaicloud/istio-operator/releases/tag/0.4.2) tag is up and contains your fix already. Thanks again for your contribution!
