### ISSUE TITLE
Upgrade k8s libs to at least 1.15

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/istio-operator#356]
**Is your feature request related to a problem? Please describe.**
The operator has rather old k8s lib versions.

I'm particularly affected by this:

https://github.com/kubernetes/apimachinery/commit/ed8af178d620cdb55580cddff6bfef9d3b00a7d7

In 1.17 the deprecated feature has been removed.

**Describe the solution you'd like to see**
Upgrade k8s to at least 1.15, but preferably 1.17

**Describe alternatives you've considered**
An alternative could be moving the API to a separate module.

**Additional context**
As of 1.17 importing k8s libraries became easier, you might want to consider moving to Go Modules:

https://github.com/kubernetes/client-go/blob/master/INSTALL.md#add-client-go-as-a-dependency%C2%A0for

**Comment by Laci21** [comment]
In the newest version we use GO modules, separate API module and k8s 1.20 libs.
