### ISSUE TITLE
Priorityclass for Istio operator?

### ISSUE THREAD

**Issue by bmacauley-reward** [banzaicloud/istio-operator#390]
**Is your feature request related to a problem? Please describe.**
We would like to add a priorityclass  of system-cluster-critical to the istio components

**Describe the solution you'd like to see**
Add priorityclass to istio-operator config

**Comment by Laci21** [comment]
Sure, we will implement this in the upcoming weeks.

**Comment by Laci21** [comment]
@bmacauley-reward, the feature is available in `0.4.11` Docker image for Istio 1.4.x versions and in `0.5.1` for Istio 1.5.x.

For the `system-cluster-critical` PriorityClass you will need K8s 1.17+, check out the [description of the field](https://github.com/banzaicloud/istio-operator/blob/release-1.5/pkg/apis/istio/v1beta1/istio_types.go#L668-L676) for more details. Let us know if it works as you expected!

**Comment by bmacauley-reward** [comment]
Thanks guys!
