### ISSUE TITLE
Update coredns configmap reconciler to use forward instead of proxy

### ISSUE THREAD

**Issue by jhynds-reward** [banzaicloud/istio-operator#391]
**Describe the bug**
The operator attempts to reconcile the coredns configmap in kube-system and overwrites the global section of it.  As of version 1.5.0 coredns (see https://github.com/coredns/coredns/issues/1443. or https://github.com/Azure/AKS/issues/1304) has deprecated the use of proxy in favour of th newer froward plugin and as such the reconcilliation causes coredns to fail and therefore the cluster to become unstable/unusable.

**Steps to reproduce the issue:**
 - Deploy coredns 1.5.0+
 - Deploy the coredns configmap with the gloabl:53 blokc using forward instead of proxy
 - Deploy the operator
 - The reconciliation will modify the configmap to replace the global:53 block with the proxy version
 - Coredns crashes,  related pods crash/fail on error

**Expected behavior**
The block that is being injected/changed should be updated to use forward instead of proxy when coredns version is 1.5.0+ (direct replacement of plugin/keyword is all that is required)

**Additional context**
istio-operator: release 1.4
coredns: 1.5.0 or above

**Comment by jhynds-reward** [comment]
Block in coredns.go that handles the reconcilliation/overwrite:

![Screenshot 2020-03-10 at 09 55 20](https://user-images.githubusercontent.com/56545771/76301067-99f82300-62b5-11ea-9d8f-6af898242ce4.png)

Updated configmap with forward plugin:

![Screenshot 2020-03-10 at 09 55 31](https://user-images.githubusercontent.com/56545771/76301153-b8f6b500-62b5-11ea-8370-5ad719ea3333.png)

**Comment by waynz0r** [comment]
@jhynds-reward,

thanks for reporting this!

**Comment by bmacauley-reward** [comment]
This bug is pretty critical...it literally breaks coredns and starts a cascade of failures through EKS/kubernetes

This results in us having to rebuild the cluster...done it twice today :/

**Comment by Laci21** [comment]
@jhynds-reward and @bmacauley-reward, this should be fixed in `0.4.11` Docker image for Istio 1.4.x versions and in `0.5.1` for Istio 1.5.x.
