### ISSUE TITLE
Kiali support

### ISSUE THREAD

**Issue by martonsereg** [banzaicloud/istio-operator#40]

**Comment by c0ff3e** [comment]
Yes please. as istio helm have support for it.
cant live without kiali :)

**Comment by feisuzhu** [comment]
+1
Please

**Comment by matyix** [comment]
The operator's mere concern is to install (and upgrade) Istio, and nothing else. This is inline with the operator (Kubernetes controller) pattern and follows the separation of concerns pattern. 

You can always install Kiali afterwards - or if you are looking for a `one shot` Istio management tool built on top if this operator (including a UI, CLI, GraphQL API, with Jaeger, Prometheus, Grafana, and lots more) you might want to try our service mesh product.

You can start with the [Backyard CLI](https://github.com/banzaicloud/backyards-cli) or read the [release announcement](https://banzaicloud.com/blog/backyards-release-1-0/).

If you are in quick-start mod mode and want to have a production Istio environment with all the above in minutes just hit: `curl https://getbackyards.sh | sh && backyards install -a --run-demo`
