### ISSUE TITLE
no matches for kind HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by satishmane** [banzaicloud/istio-operator#454]
**Describe the bug**

helm install --name=istio-operator --namespace=istio-system banzaicloud-stable/istio-operator --version 0.0.51
===
NAME                   READY   STATUS             RESTARTS   AGE
pod/istio-operator-0   1/2     CrashLoopBackOff   5          5m29s
Log
===
{"level":"error","ts":1593166431.6729662,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":{"Group":"autoscaling","Kind":"HorizontalPodAutoscaler"},"error":"no matches for kind \"HorizontalPodAutoscaler\" in version \"autoscaling/v2beta2\""

**Steps to reproduce the issue:**
helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
helm install --name=istio-operator --namespace=istio-system banzaicloud-stable/istio-operator

**Expected behavior**

it should install istio 1.6.3 

**Screenshots**

**Additional context**

**Comment by Laci21** [comment]
@satishmane, thanks for the issue!

What is your Kubernetes version and which cloud provider and Kubernetes distribution are you using?

**Comment by Laci21** [comment]
Also, what does this say to you?

```bash
kubectl api-versions | grep autoscaling
```

**Comment by satishmane** [comment]
thanks @Laci21 

Kubernetes version
================

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T17:02:08Z", GoVersion:"go1.13.12", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

cloud provider
==========
Google GKE

kubectl api-versions | grep autoscaling
============================
autoscaling/v1
autoscaling/v2beta1
internal.autoscaling.k8s.io/v1alpha1

**Comment by Laci21** [comment]
The Istio operator supports Kubernetes 1.15.0+: https://github.com/banzaicloud/istio-operator#istio-operator-installation
You are on `v1.14.10-gke.36`, so please try with a higher Kubernetes version to be able to properly use the operator.

Also, you should have `autoscaling/v2beta2` enabled on your cluster, which should be the case by default with higher Kubernetes versions on GKE.

**Comment by satishmane** [comment]
@Laci21 thanks
