### ISSUE TITLE
side car auto injection did not inject side car when pod deployed in namespace enabled for istio injection

### ISSUE THREAD

**Issue by satishmane** [banzaicloud/istio-operator#455]
**Describe the bug**

istio side car not injected into pod that was deployed istio injection enabled namespace

**Steps to reproduce the issue:**

helm install --name=istio-operator --namespace=istio-system banzaicloud-stable/istio-operator 0.0.48
istio installed successfully.

NAME                   READY   STATUS    RESTARTS   AGE
pod/istio-operator-0   2/2     Running   0          19m

NAME                                             TYPE               CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/istio-operator                     ClusterIP           x.x.x.x            <none>        443/TCP    19m
service/istio-operator-authproxy    ClusterIP           x.x.x.x     <none>        8443/TCP   19m
service/istio-operator-webhook     ClusterIP           x.x.x.x    <none>        443/TCP    18m

labelled namespace
================
kubectl label namespace test istio-injection=enabled

Deployed a pod. No side car injection

**Expected behavior**

Pod should be injected with istio side car

**Additional context**

kubernetes cluster firewall rules does contain 443 port in allowed list

For kubernetes version and cloud provide. Added info in below issue

https://github.com/banzaicloud/istio-operator/issues/454

**Comment by Laci21** [comment]
The Istio operator manages the sidecar injection enabled namespaces for you with this field in the Istio CR: https://github.com/banzaicloud/istio-operator/blob/release-1.6/config/samples/istio_v1beta1_istio.yaml#L14-L15

You need to add the desired namespace's name (`test` in your case) to this array, the operator will label the namespace and then you should be able to deploy pods to that namespace with sidecars injected. So for you, it could look like: 
```yaml
  autoInjectionNamespaces:
  - "test"
```

**Comment by satishmane** [comment]
@Laci21 thanks
But do I need to edit istio operator yaml? OR is there way I can add namespaces post installation of istio operator. Because if I create new namespaces, how do I enable it from command line

**Comment by Laci21** [comment]
You just need to edit the `Istio` CR on your cluster post installation. Something like this with a one liner: 
```bash
kubectl patch istio -n istio-system istio-sample --type=json -p='[{"op": "replace", "path": "/spec/autoInjectionNamespaces", "value": [default, test]}]'
```

**Comment by satishmane** [comment]
@Laci21 thanks. 
I was aware of something like "istioctl manifest generate -f patch.yaml". But thought of knowing banzai istio operator. 

thank again. Now I will test and update here.

**Comment by Laci21** [comment]
For the Banzai Cloud Istio Operator you don't need to use istioctl at all.

You are welcome, I'm closing this, please feel free to reopen if you have further issues with this.

**Comment by satishmane** [comment]
@Laci21 
Hi,
I installed istio 1.5 version as below. In order to apply patch, I do not see istio kind in istio-system namespace. 

helm install --name banzai-istio-operator-1-5 banzaicloud-stable/istio-operator --version 0.0.48 --namespace istio-system

NAME:   banzai-istio-operator-1-5
LAST DEPLOYED: Tue Jun 30 12:54:35 2020
NAMESPACE: istio-system
STATUS: DEPLOYED

RESOURCES:
==> v1/Pod(related)
NAME                         READY  STATUS             RESTARTS  AGE
banzai-istio-operator-1-5-0  0/2    ContainerCreating  0         0s

==> v1/ServiceAccount
NAME                                 SECRETS  AGE
banzai-istio-operator-1-5-authproxy  1        0s
banzai-istio-operator-1-5            1        0s

==> v1beta1/CustomResourceDefinition
NAME                               AGE
meshgateways.istio.banzaicloud.io  0s
istios.istio.banzaicloud.io        0s
remoteistios.istio.banzaicloud.io  0s

==> v1/ClusterRole
NAME                                 AGE
banzai-istio-operator-1-5-authproxy  0s
banzai-istio-operator-1-5            0s

==> v1/ClusterRoleBinding
NAME                                 AGE
banzai-istio-operator-1-5-authproxy  0s
banzai-istio-operator-1-5            0s

==> v1/Service
NAME                                 TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)   AGE
banzai-istio-operator-1-5-authproxy  ClusterIP  172.19.160.43  <none>       8443/TCP  0s
banzai-istio-operator-1-5            ClusterIP  172.19.159.40  <none>       443/TCP   0s

==> v1/StatefulSet
NAME                       DESIRED  CURRENT  AGE
banzai-istio-operator-1-5  1        1        0s


kubectl get pods -n istio-system

NAME                          READY   STATUS    RESTARTS   AGE
banzai-istio-operator-1-5-0   2/2     Running   0          7s

**Comment by Laci21** [comment]
It seems fine to me. `kubectl -n=istio-system get istios` should return the Istio CR.

**Comment by satishmane** [comment]
@Laci21 

It did not return anything...

kubectl get pods -n istio-system
NAME                          READY   STATUS    RESTARTS   AGE
banzai-istio-operator-1-5-0   2/2     Running   0          110s

 kubectl get istio -n istio-system
No resources found in istio-system namespace.

 kubectl get istios -n istio-system
No resources found in istio-system namespace.

**Comment by Laci21** [comment]
Oh, okay sorry. So you've installed the istio operator and the `istios.istio.banzaicloud.io` CRD to your cluster, but now you need to create an Istio CR as well. You can find example Istio CRs here: https://github.com/banzaicloud/istio-operator/tree/release-1.5/config/samples.

You can create one e.g. with: `kubectl create -n istio-system -f config/samples/istio_v1beta1_istio.yaml`

**Comment by satishmane** [comment]
thanks @Laci21 

Ok, Do I need to uninstall istio operator before creating @Laci21 CR. OR I can separately create CR in addition to helm based istio operator installation

**Comment by Laci21** [comment]
You need the operator to reconcile based on the Istio CR, so do NOT remove the operator, but create it alongside the operator.

**Comment by satishmane** [comment]
@Laci21 
thanks. finally worked.
