### ISSUE TITLE
global.proxy.privileged=true - how do we set in patch to enable tcpdump in side car

### ISSUE THREAD

**Issue by satishmane** [banzaicloud/istio-operator#477]
**Describe the bug**

Side car proxy does not support tcpdump command when executed using kubectl exex

**Steps to reproduce the issue:**

kubectl exec it pods/<podname> -c istio-proxy -- sh sudo tcpdump

**Expected behavior**
sudo tcpdump should run

What value should be set in istio operator patch

e.g. is below command right?
kubectl patch istio my-istio -n istio-system --type=json -p='[{"op": "replace", "path": "/spec/proxy/privileged", "value": true}]'

**Comment by Laci21** [comment]
The patch command looks right and then the pod with the sidecar proxy should be restarted so that it gets the new config. Doesn't it work?

**Comment by satishmane** [comment]
yes, thanks it works.
