### ISSUE TITLE
no certs in /etc/istio-certs mount

### ISSUE THREAD

**Issue by satishmane** [banzaicloud/istio-operator#485]
Hi,
I applied below annotations to my pod in order to use use istio provided certs. But there are no certs listed in /etc/istio-certs volumeMount. If I install istio using istioctl, then it works .. I can see certs in my pod's istio side car volumeMount. But same does not work in banzai helm based istio installation. I tried patching mountMtlsCerts to true, but did not work. 
Can you please suggest where do I need to enable in banzai istio CR. 

Banzai Istio version is 1.6.4

proxy.istio.io/config: \|
   proxyMetadata:
      OUTPUT_CERTS: /etc/istio-certs
      SECRET_TTL: 10m
  sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium": "Memory"}}]'
  sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]'

**Comment by satishmane** [comment]
I do not see global.mountMtlsCerts set to true  in the istio-sidecar-injector map even though I applied patch succesfully and I can see it set to true CR. Is this the reason?

**Comment by Laci21** [comment]
Hi,

Yeah, that seems to be the issue, let me verify and prepare a quick fix.

**Comment by Laci21** [comment]
The `banzaicloud/istio-operator:0.6.9` docker image should fix this problem, could you please update your istio-operator statefulset to use this version and verify that it solves the problem for you?

**Comment by satishmane** [comment]
@Laci21  thank you . I will apply and update here soon

**Comment by satishmane** [comment]
@Laci21 
Now istio-certs volume and volumeMount as /etc/certs are getting added to istio side car as part of autoInjection.
But istio-certs volume points to istio-default instead of emptyDir medium : memory

So when I do 
exec -it <my pod> -n <namepsace> -c istio-proxy -- ls -ltr "/etc/certs"

total found files is 0

**Comment by satishmane** [comment]
@Laci21 
I attached service account name to my pod so that side car injector will attach istio-certs volume to istio.mypodserviceaccount secret. But should not this istio.mypodserviceaccount secret be automatically created by istio side injector? 

Can you please help with fix
