### ISSUE TITLE
istio proxy unnecessary routes logs

### ISSUE THREAD

**Issue by satishmane** [banzaicloud/istio-operator#506]
**Describe the bug**

Istio proxy logging too many entries related to istio routes, especially for kafka / zookeeper pods. If I disable accessLog, then will that stop everything or logging below unnecessary logs

**Steps to reproduce the issue:**

Enable mtls on kafka/zookeeper

**Expected behavior**

Istio proxy log should have only envoy start up, istiod config sync up log

**Additional context**

{"requested_server_name":"-","bytes_received":"108","istio_policy_status":"-","bytes_sent":"406","upstream_cluster":"PassthroughCluster","downstream_remote_address":"172.18.0.42:45784","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.0.42:45786","duration":"15","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.17.1.3:5432","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-02T14:50:14.238Z","method":"-","request_id":"-","upstream_host":"172.17.1.3:5432","x_forwarded_for":"-"}
{"bytes_sent":"418","upstream_cluster":"PassthroughCluster","downstream_remote_address":"172.18.0.42:45788","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.0.42:45790","duration":"7","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.17.1.3:5432","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-02T14:50:14.249Z","method":"-","request_id":"-","upstream_host":"172.17.1.3:5432","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"127","istio_policy_status":"-"}
{"start_time":"2020-09-02T14:50:14.255Z","method":"-","request_id":"-","upstream_host":"172.17.1.3:5432","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"119","istio_policy_status":"-","bytes_sent":"3101","upstream_cluster":"PassthroughCluster","downstream_remote_address":"172.18.0.42:45792","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.0.42:45794","duration":"7","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.17.1.3:5432","user_agent":"-","response_code":"0","response_flags":"-"}
{"upstream_cluster":"PassthroughCluster","downstream_remote_address":"172.18.0.42:45796","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.0.42:45798","duration":"9","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.17.1.3:5432","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-02T14:50:14.263Z","method":"-","request_id":"-","upstream_host":"172.17.1.3:5432","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"253","istio_policy_status":"-","bytes_sent":"43011"}
{"bytes_sent":"697","upstream_cluster":"PassthroughCluster","downstream_remote_address":"172.18.0.42:45800","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.0.42:45802","duration":"9","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.17.1.3:5432","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-02T14:50:14.285Z","method":"-","request_id":"-","upstream_host":"172.17.1.3:5432","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"416","istio_policy_status":"-"}
{"bytes_sent":"403","upstream_cluster":"PassthroughCluster","downstream_remote_address":"172.18.0.42:45804","authority":"-","path":"-","protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.0.42:45806","duration":"19","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.17.1.3:5432","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-02T14:50:14.293Z","method":"-","request_id":"-","upstream_host":"172.17.1.3:5432","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"225","istio_policy_status":"-"}
{"protocol":"-","upstream_service_time":"-","upstream_local_address":"172.18.0.42:45810","duration":"10","upstream_transport_failure_reason":"-","route_name":"-","downstream_local_address":"172.17.1.3:5432","user_agent":"-","response_code":"0","response_flags":"-","start_time":"2020-09-02T14:50:14.311Z","method":"-","request_id":"-","upstream_host":"172.17.1.3:5432","x_forwarded_for":"-","requested_server_name":"-","bytes_received":"592","istio_policy_status":"-","bytes_sent":"17848","upstream_cluster":"PassthroughCluster","downstream_remote_address":"172.18.0.42:45808","authority":"-","path":"-"}

**Comment by Laci21** [comment]
You should be able to disable only access logging if you set [this field](https://github.com/banzaicloud/istio-operator/blob/release-1.7/config/samples/istio_v1beta1_istio.yaml#L115) to `""` and then restart your pods

**Comment by satishmane** [comment]
Hi @Laci21 
thanks. worked. I thought I can use this annotation sidecar.istio.io/logLevel to switch off at pod level
