### ISSUE TITLE
istio 1.6.8 - sidecar.istio.io/proxyCPULimit and other resource annotations not overriding global resources

### ISSUE THREAD

**Issue by satishmane** [banzaicloud/istio-operator#509]
**Describe the bug**

Added below resource annotations in a pod to override global settings. But it does not work. they are not overriding when istio proxy is injected

        sidecar.istio.io/proxyCPULimit: "500m"
        sidecar.istio.io/proxyMemoryLimit: "500Mi"
        sidecar.istio.io/proxyCPU: "300m"
        sidecar.istio.io/proxyMemory: "300Mi"

Can you please validate if condition at below code line is correct
https://github.com/banzaicloud/istio-operator/blob/release-1.6/pkg/resources/sidecarinjector/configmap_sidecar_injector.go#L398

**Steps to reproduce the issue:**

Add proxy cpu annotations in a pod. Describe pod and see istio proxy resource section. 

**Expected behavior**

Pod level resource annotations should override global resources settings

**Comment by Laci21** [comment]
Thanks for reporting this! The issue should be fixed in Docker image versions `0.6.13` and `0.7.2`.
