### ISSUE TITLE
Differences to the official Istio operator

### ISSUE THREAD

**Issue by Smirl** [banzaicloud/istio-operator#543]
**Is your feature request related to a problem? Please describe.**
I have been looking to upgrade from Istio 1.4 using helm to 1.5+ using the istio operator. Reading the official docs the operator is the way to go. Googling the istio operator also returns results for this project. It is confusing that both have the same name, and there is no mention of the official operator on the README.

**Describe the solution you'd like to see**
A clear shout out to the official [istio/operator](https://github.com/istio/istio/tree/master/operator) and the differences (if any) between them. Sorry if these projects are actually the same project, a quick look at the code makes them look quite different.

**Describe alternatives you've considered**
Alternatively, renaming this project, or deprecating it in favour of the official one. There is no need to have competing projects, we are all on the same side. (again apologies if there is collaboration between the projects, I'm not clear).

**Comment by matyix** [comment]
@Smirl This project has been open sourced around 9+ months before any `official` or other Istio operator has been ever built, see the [initial release announcement](https://banzaicloud.com/blog/istio-operator/). We have built it for our own internal needs, as it's a core part of our [Backyards](https://banzaicloud.com/products/backyards/) service mesh platform/Istio distribution and it's used in production by our customers and plenty of open source users. We don't plan to deprecate it, as it's under active production use and development.

One of the significant difference is that the Banzai Cloud Istio operator supports multi cluster scenarios (single/multi mesh) and multiple gateways (but there are lots more). As the operator has been built for [Backyards](https://banzaicloud.com/products/backyards/) and it’s a core part of it we carry some Istio/Envoy changes or features which are either not fixed or not available upstream yet, but eventually they will land there - we just needed to fix it for our Backyards customers. 

For further details you might want to go through the Backyards [documentation](https://banzaicloud.com/docs/backyards/overview/) or read more in the [blogs](https://banzaicloud.com/tags/backyards/).

**Comment by Smirl** [comment]
Thanks for the super speedy reply @matyix! I think the other istio operator supports pretty much everything with customisation, helm value changes, and resource overlays. However, no need to deprecate this project if you don't need to, that wasn't what I was getting at.

It would be great to see that paragraph you shared in the readme so everyone has the context/history for the project. Happy to raise a PR for it if you like.
