### ISSUE TITLE
Integrate with the Banzai Cloud Kafka operator

### ISSUE THREAD

**Issue by matyix** [banzaicloud/istio-operator#62]
**Is your feature request related to a problem? Please describe.**

Add support/integration with the Banzai Cloud Kafka Operator. The Kafka Operator already orchestrates an Envoy proxy in order to route external broker access towards the broker pod - instead of relying on the load balancer's e.g. `round-robin` feature. While brokers come and go (autoscaling, failovers, etc) the Kafka operator already generates complex Envoy configs - adding mTLS, etc complicates things even more. 

**Describe the solution you'd like to see**

Add support for Kafka, by wiring brokers into the mesh. Also, add support for the Envoy Kafka protocol filter once is pushed upstream.

**Comment by baluchicken** [comment]
Banzai Cloud's Supertubes comes with a full mesh support. If you are interested please check https://banzaicloud.com/docs/backyards/overview/. If you want to read more about the key benefits of integrating Kafka with the mesh please read our [blog post](https://banzaicloud.com/blog/kafka-on-istio-benefits/)
