### ISSUE TITLE
Istio-operator is not cleaned up properly on Kubernetes 1.20+

### ISSUE THREAD

**Issue by khernyo** [banzaicloud/istio-operator#643]
**Describe the bug**

When deleting an Istio resource on Kubernetes 1.20, some resources created by istio-operator are not deleted.
This is already a problem, but there is a more serious issue: one of the resources left in the cluster is a ValidatingWebhookConfiguration, and it prevents the reconciliation of any further Istio resources. Deleting the
leftover ValidatingWebhookConfiguration unblocks the reconciliation process which should now succeed.

There are three other resource types which are not cleaned up either: ClusterRole, ClusterRoleBinding and MutatingWebhookConfiguration. These don't cause any visible issues, though.

The cause is that in Kubernetes 1.20, ownership reference between cluster scoped and namespace scoped resources is disallowed, and such owner references are not followed by the GC.

For more information, see the note in section "Owners and Dependents" of https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents

**Steps to reproduce the issue:**

1. Create a cluster with Kubernetes 1.20
1. Install istio-operator (e.g. version 0.9.4)
1. List the ValidatingWebhookConfiguration resources. There should be only one, named "istio-operator-webhook"
1. Create an Istio resource
1. When the Istio resource is reconciled, delete it
1. List the ValidatingWebhookConfiguration resources again: There will be a new ValidatingWebhookConfiguration, named "istiod-...", which is never deleted

**Expected behavior**

No resources are left in the cluster inadvertently. E.g. leaving CRDs in the cluster is fine, but any resources which prevent
the correct functioning of the cluster is not.

**Additional context**

Kubernetes v1.20.2
Istio-operator v0.9.4

**Comment by Laci21** [comment]
This is fixed in the latest version.
