### ISSUE TITLE
Multicluster docs/impl out of sync

### ISSUE THREAD

**Issue by rshriram** [banzaicloud/istio-operator#68]
Nice work on the operator folks.. With regard to the multicluster setup, we have updated the multicluster setup a while ago. You no longer need a vpn for the single control plane-noHA option - i.e. no longer need unique pod CIDRs..

Secondly, there is a much more simpler multicluster option with two control planes (one on each cluster), and pods communicating with each other via the gateways. I believe the operator can be of great help in this setup to spit out the global services (services that are visible across clusters), and assign unique VIPs to these services.. 

https://preliminary.istio.io/docs/setup/kubernetes/multicluster-install/gateways/
I would be happy to give you more details or the workflow.

**Comment by waynz0r** [comment]
@rshriram thanks for checking out the operator.

If you are referring the split-horizon EDS setup, afaik it needs Istio v1.1, so it is something that we are planning to add into the Istio v1.1 support of the operator.

As for the `gateway multi-cluster` setup, it is also on our roadmap. (see #33)
