### ISSUE TITLE
Any custom builds with 1.1 ?

### ISSUE THREAD

**Issue by rshriram** [banzaicloud/istio-operator#69]
are there any releases/branches that support the 1.1 series (or the rc0)? if not, we would be happy to help..
cc @costinm @sdake

**Comment by matyix** [comment]
Hello @rshriram - thanks for reaching out. There is no branch yet, we were just about to kick it off (see #30). Any help is more than welcome, so if you are willing to work on this we'd be happy to accept PR's/work with you guys on this.

**Comment by rshriram** [comment]
Also, could you guys
