### ISSUE TITLE
Warnings about deprecated api version

### ISSUE THREAD

**Issue by dmndru** [banzaicloud/istio-operator#770]
**Describe the bug**
There are warnings in operator logs about deprecated api versions:
`W1012 13:23:08.822542       1 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
W1012 13:23:38.623660       1 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration`

**Steps to reproduce the issue:**
See logs of the istio operator:
`kubectl logs istio-operator-0 manager | grep warning`

**Additional context**
We run istio operator of version 0.10.6 on kubernetes 1.20

**Comment by Laci21** [comment]
Hi @dmndru,

Thanks for reporting!

Based on the logs there should be an easy fix for this by using `admissionregistration.k8s.io/v1` for the webhook resources. We'll take a look, but we have some other priorities right now so you might except some delay on this.

Also, if you fancy, feel free to take a stab at it and open PR, it would be appreciated.
