### ISSUE TITLE
Panic during multicluster attach

### ISSUE THREAD

**Issue by john-a-joyce** [banzaicloud/istio-operator#778]
**Describe the bug**
In a multicluster scenario the istio-operator throws a panic and crash loops.   This is on version 1.7.7

**Steps to reproduce the issue:**
Create two kind clusters using the default configuration.   Follow the multicluster instructions on the blog page.   After the "attach" step the istio-operator goes into a crash loop.   NOTE:  this was a slight misconfiguration because by default the kubeconfig for the kind clusters uses a 127.0.0.0 address and that address can't be used from one within one cluster to connect to the other but can be used by smm-cli to access both clusters API servers.   

**Expected behavior**
Second cluster can attach. 

**Screenshots**

**Additional context**
Note:  when using a kind configuration which allows access to the 2nd cluster this crash is not seen and the cluster gets attached. 

root@bxb-ds-84:~/go/src/cisco-app-networking/greatbear-work# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-05-01T02:11:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
root@bxb-ds-84:~/go/src/cisco-app-networking/greatbear-work# kind version
kind v0.7.0 go1.13.6 linux/amd64

**Comment by john-a-joyce** [comment]
Here is the log from istio-operator. 

{"level":"info","ts":"2021-10-20T17:50:27.041Z","logger":"entrypoint","msg":"setting up client for manager"}
{"level":"info","ts":"2021-10-20T17:50:27.041Z","logger":"entrypoint","msg":"watch all namespaces"}
{"level":"info","ts":"2021-10-20T17:50:27.041Z","logger":"entrypoint","msg":"setting up manager"}
I1020 17:50:28.092416       1 request.go:655] Throttling request took 1.038430805s, request: GET:https://10.96.0.1:443/apis/batch/v1?timeout=32s
{"level":"info","ts":"2021-10-20T17:50:28.250Z","logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"127.0.0.1:8080"}
{"level":"info","ts":"2021-10-20T17:50:28.251Z","logger":"entrypoint","msg":"registering components"}
{"level":"info","ts":"2021-10-20T17:50:28.251Z","logger":"entrypoint","msg":"setting up scheme"}
{"level":"info","ts":"2021-10-20T17:50:28.252Z","logger":"entrypoint","msg":"setting up controller"}
{"level":"info","ts":"2021-10-20T17:50:28.316Z","logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-istio-config"}
{"level":"info","ts":"2021-10-20T17:50:28.316Z","logger":"controller-runtime.webhook","msg":"registering webhook","path":"/spiffe-trust-bundle"}
{"level":"info","ts":"2021-10-20T17:50:28.316Z","logger":"wh-cert-provisioner","msg":"certificate is invalid, regenerate"}
{"level":"info","ts":"2021-10-20T17:50:39.420Z","logger":"entrypoint","msg":"starting the Cmd."}
I1020 17:50:39.421009       1 leaderelection.go:243] attempting to acquire leader lease smm-system/istio-operator-v110x-leader...
{"level":"info","ts":"2021-10-20T17:50:39.433Z","logger":"trustbundle","msg":"controlplane added","key":"istio-system/cp-v110x/e5f14763-257c-4c84-800b-51d4b3ce03c5"}
{"level":"info","ts":"2021-10-20T17:50:39.521Z","logger":"entrypoint","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":"2021-10-20T17:50:39.521Z","logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
{"level":"info","ts":"2021-10-20T17:50:39.521Z","logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":"2021-10-20T17:50:39.522Z","logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
{"level":"info","ts":"2021-10-20T17:50:39.522Z","logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
I1020 17:50:56.227068       1 leaderelection.go:253] successfully acquired lease smm-system/istio-operator-v110x-leader
{"level":"info","ts":"2021-10-20T17:50:56.227Z","logger":"entrypoint.controller.meshgateway-controller","msg":"Starting EventSource","source":"kind source: istio.banzaicloud.io/v1beta1, Kind=MeshGateway"}
{"level":"info","ts":"2021-10-20T17:50:56.227Z","logger":"entrypoint.controller.istio-controller","msg":"Starting EventSource","source":"kind source: istio.banzaicloud.io/v1beta1, Kind=Istio"}
{"level":"info","ts":"2021-10-20T17:50:56.227Z","logger":"entrypoint.controller.remoteistio-controller","msg":"Starting EventSource","source":"kind source: istio.banzaicloud.io/v1beta1, Kind=RemoteIstio"}
{"level":"info","ts":"2021-10-20T17:50:56.227Z","logger":"entrypoint.controller.istio-controller","msg":"Starting EventSource","source":"kind source: istio.banzaicloud.io/v1beta1, Kind=RemoteIstio"}
{"level":"info","ts":"2021-10-20T17:50:56.328Z","logger":"entrypoint.controller.meshgateway-controller","msg":"Starting EventSource","source":"kind source: /v1, Kind=ServiceAccount"}
{"level":"info","ts":"2021-10-20T17:50:56.328Z","logger":"entrypoint.controller.istio-controller","msg":"Starting EventSource","source":"kind source: /v1, Kind=Service"}
{"level":"info","ts":"2021-10-20T17:50:56.328Z","logger":"entrypoint.controller.remoteistio-controller","msg":"Starting EventSource","source":"kind source: istio.banzaicloud.io/v1beta1, Kind=Istio"}
{"level":"info","ts":"2021-10-20T17:50:56.328Z","logger":"entrypoint.controller.remoteistio-controller","msg":"Starting EventSource","source":"kind source: /v1, Kind=Pod"}
{"level":"info","ts":"2021-10-20T17:50:56.329Z","logger":"wh-cert-provisioner","msg":"certificate is invalid, regenerate"}
{"level":"info","ts":"2021-10-20T17:50:56.428Z","logger":"entrypoint.controller.istio-controller","msg":"Starting EventSource","source":"kind source: /v1, Kind=Namespace"}
{"level":"info","ts":"2021-10-20T17:50:56.428Z","logger":"entrypoint.controller.meshgateway-controller","msg":"Starting EventSource","source":"kind source: /v1, Kind=Role"}
{"level":"info","ts":"2021-10-20T17:50:56.429Z","logger":"entrypoint.controller.remoteistio-controller","msg":"Starting EventSource","source":"kind source: /v1, Kind=service"}
{"level":"info","ts":"2021-10-20T17:50:56.429Z","logger":"entrypoint.controller.remoteistio-controller","msg":"Starting EventSource","source":"kind source: /v1, Kind=Namespace"}
{"level":"info","ts":"2021-10-20T17:50:56.529Z","logger":"entrypoint.controller.remoteistio-controller","msg":"Starting Controller"}
{"level":"info","ts":"2021-10-20T17:50:56.529Z","logger":"entrypoint.controller.meshgateway-controller","msg":"Starting EventSource","source":"kind source: /v1, Kind=RoleBinding"}
{"level":"info","ts":"2021-10-20T17:50:56.530Z","logger":"entrypoint.controller.remoteistio-controller","msg":"Starting workers","worker count":1}
{"level":"info","ts":"2021-10-20T17:50:56.530Z","logger":"entrypoint.controller.istio-controller","msg":"Starting EventSource","source":"kind source: istio.banzaicloud.io/v1beta1, Kind=MeshGateway"}
{"level":"info","ts":"2021-10-20T17:50:56.530Z","logger":"entrypoint.controller.istio-controller","msg":"Starting EventSource","source":"kind source: admissionregistration.k8s.io/v1beta1, Kind=ValidatingWebhookConfiguration"}
{"level":"info","ts":"2021-10-20T17:50:56.542Z","logger":"remote-istio-controller","msg":"remoteconfig status updated","trigger":"istio-system/kindedge","correlationID":"66571016-005b-4a15-b00e-9a2dcf746a21","cluster":"kindedge","status":"Reconciling"}
{"level":"info","ts":"2021-10-20T17:50:56.542Z","logger":"remote-istio-controller","msg":"begin reconciling remote istio","trigger":"istio-system/kindedge","correlationID":"66571016-005b-4a15-b00e-9a2dcf746a21","cluster":"kindedge"}
{"level":"info","ts":"2021-10-20T17:50:56.542Z","logger":"remote-istio-controller","msg":"k8s config found","trigger":"istio-system/kindedge","correlationID":"66571016-005b-4a15-b00e-9a2dcf746a21","cluster":"kindedge"}
{"level":"info","ts":"2021-10-20T17:50:56.546Z","logger":"remote-istio-controller","msg":"reconciling remote istio","trigger":"istio-system/kindedge","correlationID":"66571016-005b-4a15-b00e-9a2dcf746a21","cluster":"kindedge","cluster":"kindedge"}
{"level":"info","ts":"2021-10-20T17:50:56.547Z","logger":"remote-istio-controller","msg":"reconciling CRDs","trigger":"istio-system/kindedge","correlationID":"66571016-005b-4a15-b00e-9a2dcf746a21","cluster":"kindedge","cluster":"kindedge"}
E1020 17:50:56.608627       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 535 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1731ca0, 0x2551960)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1731ca0, 0x2551960)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/banzaicloud/istio-operator/pkg/k8sutil.(*Cached).RESTMapping(0xc0004fc660, 0x1902fc9, 0x14, 0x164e29c, 0x18, 0xc0011d21d0, 0x1, 0x1, 0x0, 0x0, ...)
        /go/src/github.com/banzaicloud/istio-operator/pkg/k8sutil/cached_rest_mapper.go:112 +0x31
sigs.k8s.io/controller-runtime/pkg/cache/internal.createStructuredListWatch(0x1902fc9, 0x14, 0x18f2838, 0x2, 0x164e29c, 0x18, 0xc000ea8680, 0x80b7cf503b519946, 0xc001597020, 0x4c03cf)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:238 +0x142
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).addInformerToMap(0xc000ea8680, 0x1902fc9, 0x14, 0x18f2838, 0x2, 0x164e29c, 0x18, 0x1b04b30, 0xc000dddb80, 0x0, ...)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:208 +0x159
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Get(0xc000ea8680, 0x1b2c7e8, 0xc000048018, 0x1902fc9, 0x14, 0x18f2838, 0x2, 0x164e29c, 0x18, 0x1b04b30, ...)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:180 +0x407
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*InformersMap).Get(0xc000618700, 0x1b2c7e8, 0xc000048018, 0x1902fc9, 0x14, 0x18f2838, 0x2, 0x164e29c, 0x18, 0x1b04b30, ...)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go:103 +0x18a
sigs.k8s.io/controller-runtime/pkg/cache.(*informerCache).Get(0xc0002181b8, 0x1b2c7e8, 0xc000048018, 0x0, 0x0, 0xc00072a0a0, 0x1b, 0x1b50098, 0xc000dddb80, 0xc001c9c060, ...)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go:60 +0x1af
sigs.k8s.io/controller-runtime/pkg/client.(*delegatingReader).Get(0xc0002890c0, 0x1b2c7e8, 0xc000048018, 0x0, 0x0, 0xc00072a0a0, 0x1b, 0x1b50098, 0xc000dddb80, 0x1, ...)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go:130 +0x1a5
github.com/banzaicloud/istio-operator/pkg/crds.(*CRDReconciler).Reconcile(0xc0011bef50, 0xc001422600, 0x1b35850, 0xc000284770, 0xc000123d60, 0x2)
        /go/src/github.com/banzaicloud/istio-operator/pkg/crds/crds.go:182 +0x58b
github.com/banzaicloud/istio-operator/pkg/remoteclusters.(*Cluster).reconcileCRDs(0xc001034000, 0xc0005a1c00, 0xc000dd4000, 0x0, 0x0)
        /go/src/github.com/banzaicloud/istio-operator/pkg/remoteclusters/reconcile_crds.go:62 +0x205
github.com/banzaicloud/istio-operator/pkg/remoteclusters.(*Cluster).Reconcile(0xc001034000, 0xc0005a1c00, 0xc000dd4000, 0xc0009e3030, 0x8)
        /go/src/github.com/banzaicloud/istio-operator/pkg/remoteclusters/cluster.go:285 +0xf9
github.com/banzaicloud/istio-operator/pkg/controller/remoteistio.(*ReconcileRemoteConfig).reconcile(0xc00083a320, 0xc0005a1c00, 0xc000dd4000, 0x1b35850, 0xc0004d0ee0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/banzaicloud/istio-operator/pkg/controller/remoteistio/remoteistio_controller.go:331 +0x651
github.com/banzaicloud/istio-operator/pkg/controller/remoteistio.(*ReconcileRemoteConfig).Reconcile(0xc00083a320, 0x1b2c858, 0xc000923cb0, 0xc000d1c110, 0xc, 0xc000d1c0f0, 0x8, 0xc000923cb0, 0xc000030000, 0x17bd280, ...)
        /go/src/github.com/banzaicloud/istio-operator/pkg/controller/remoteistio/remoteistio_controller.go:261 +0x8b1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000d0e820, 0x1b2c7b0, 0xc000636040, 0x17839e0, 0xc000297500)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000d0e820, 0x1b2c7b0, 0xc000636040, 0x0)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x1b2c7b0, 0xc000636040)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0009e6750)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001597f50, 0x1afa700, 0xc000923bf0, 0xc000636001, 0xc0003063c0)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009e6750, 0x3b9aca00, 0x0, 0x1, 0xc0003063c0)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1b2c7b0, 0xc000636040, 0xc0004456b0, 0x3b9aca00, 0x0, 0x1)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1b2c7b0, 0xc000636040, 0xc0004456b0, 0x3b9aca00)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213 +0x40d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1539d31]

goroutine 535 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1731ca0, 0x2551960)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/banzaicloud/istio-operator/pkg/k8sutil.(*Cached).RESTMapping(0xc0004fc660, 0x1902fc9, 0x14, 0x164e29c, 0x18, 0xc0011d21d0, 0x1, 0x1, 0x0, 0x0, ...)
        /go/src/github.com/banzaicloud/istio-operator/pkg/k8sutil/cached_rest_mapper.go:112 +0x31
sigs.k8s.io/controller-runtime/pkg/cache/internal.createStructuredListWatch(0x1902fc9, 0x14, 0x18f2838, 0x2, 0x164e29c, 0x18, 0xc000ea8680, 0x80b7cf503b519946, 0xc001597020, 0x4c03cf)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:238 +0x142
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).addInformerToMap(0xc000ea8680, 0x1902fc9, 0x14, 0x18f2838, 0x2, 0x164e29c, 0x18, 0x1b04b30, 0xc000dddb80, 0x0, ...)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:208 +0x159
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Get(0xc000ea8680, 0x1b2c7e8, 0xc000048018, 0x1902fc9, 0x14, 0x18f2838, 0x2, 0x164e29c, 0x18, 0x1b04b30, ...)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:180 +0x407
sigs.k8s.io/controller-runtime/pkg/cache/internal.(*InformersMap).Get(0xc000618700, 0x1b2c7e8, 0xc000048018, 0x1902fc9, 0x14, 0x18f2838, 0x2, 0x164e29c, 0x18, 0x1b04b30, ...)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go:103 +0x18a
sigs.k8s.io/controller-runtime/pkg/cache.(*informerCache).Get(0xc0002181b8, 0x1b2c7e8, 0xc000048018, 0x0, 0x0, 0xc00072a0a0, 0x1b, 0x1b50098, 0xc000dddb80, 0xc001c9c060, ...)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go:60 +0x1af
sigs.k8s.io/controller-runtime/pkg/client.(*delegatingReader).Get(0xc0002890c0, 0x1b2c7e8, 0xc000048018, 0x0, 0x0, 0xc00072a0a0, 0x1b, 0x1b50098, 0xc000dddb80, 0x1, ...)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go:130 +0x1a5
github.com/banzaicloud/istio-operator/pkg/crds.(*CRDReconciler).Reconcile(0xc0011bef50, 0xc001422600, 0x1b35850, 0xc000284770, 0xc000123d60, 0x2)
        /go/src/github.com/banzaicloud/istio-operator/pkg/crds/crds.go:182 +0x58b
github.com/banzaicloud/istio-operator/pkg/remoteclusters.(*Cluster).reconcileCRDs(0xc001034000, 0xc0005a1c00, 0xc000dd4000, 0x0, 0x0)
        /go/src/github.com/banzaicloud/istio-operator/pkg/remoteclusters/reconcile_crds.go:62 +0x205
github.com/banzaicloud/istio-operator/pkg/remoteclusters.(*Cluster).Reconcile(0xc001034000, 0xc0005a1c00, 0xc000dd4000, 0xc0009e3030, 0x8)
        /go/src/github.com/banzaicloud/istio-operator/pkg/remoteclusters/cluster.go:285 +0xf9
github.com/banzaicloud/istio-operator/pkg/controller/remoteistio.(*ReconcileRemoteConfig).reconcile(0xc00083a320, 0xc0005a1c00, 0xc000dd4000, 0x1b35850, 0xc0004d0ee0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/banzaicloud/istio-operator/pkg/controller/remoteistio/remoteistio_controller.go:331 +0x651
github.com/banzaicloud/istio-operator/pkg/controller/remoteistio.(*ReconcileRemoteConfig).Reconcile(0xc00083a320, 0x1b2c858, 0xc000923cb0, 0xc000d1c110, 0xc, 0xc000d1c0f0, 0x8, 0xc000923cb0, 0xc000030000, 0x17bd280, ...)
        /go/src/github.com/banzaicloud/istio-operator/pkg/controller/remoteistio/remoteistio_controller.go:261 +0x8b1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000d0e820, 0x1b2c7b0, 0xc000636040, 0x17839e0, 0xc000297500)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000d0e820, 0x1b2c7b0, 0xc000636040, 0x0)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x1b2c7b0, 0xc000636040)
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0009e6750)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001597f50, 0x1afa700, 0xc000923bf0, 0xc000636001, 0xc0003063c0)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0009e6750, 0x3b9aca00, 0x0, 0x1, 0xc0003063c0)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1b2c7b0, 0xc000636040, 0xc0004456b0, 0x3b9aca00, 0x0, 0x1)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1b2c7b0, 0xc000636040, 0xc0004456b0, 0x3b9aca00)
        /go/src/github.com/banzaicloud/istio-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/src/github.com/banzaicloud/istio-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213 +0x40d

**Comment by Laci21** [comment]
Cannot reproduce anymore.
