### ISSUE TITLE
RBAC for cleanup of distribution reports is missing

### ISSUE THREAD

**Issue by Obirah** [banzaicloud/istio-operator#876]
**Describe the bug**
When creating istiod through `IstioControlPlane` with `enableStatus: true` configured in the spec, istiod is wrting distribution reports as ConfigMaps. Those ConfigMaps currently don't get cleaned up and flood the cluster. In our case it even lead to Prometheus being OOMKilled because there are so many `kube_configmap_...` metrics coming in through kube-state-metrics.

**Steps to reproduce the issue:**
1. Deploy an `IstioControlPlane` with `enableStatus: true` in the spec.
2. Make sure istiod is running correctly and wait for a while.
3. ConfigMaps will keep on appearing without old ones getting cleaned up.

**Expected behavior**
Istiod should correctly cleanup the distribution reports so that the cluster is not flooded with ConfigMaps.

**Additional context**
I think the [istiod role](https://github.com/banzaicloud/istio-operator/blob/45eb10eeab67758f0dd88ced4dd756506ad4aaaf/internal/assets/manifests/istio-discovery/templates/role.yaml) that the operator is creating, needs the ConfigMap permissions.

**Comment by Laci21** [comment]
Hi @Obirah!

Do you know if this might be a bug upstream?

I check the file you linked upstream and they don't have this role to be able to delete ConfigMaps: https://github.com/istio/istio/blob/1.15.3/manifests/charts/istio-control/istio-discovery/templates/role.yaml

Nor here: https://github.com/istio/istio/blob/1.15.3/manifests/charts/istio-control/istio-discovery/templates/clusterrole.yaml#L69-L71

So I wonder if this works upstream at all.

Also, do I understand correctly that there should be one ConfigMap created for one istiod pod (I'm not familiar with this feature very much, just checked the code briefly)? And when one istiod pod stops then the Configmap should be deleted as well according to this line: https://github.com/istio/istio/blob/4c7b4844d71a5da7203ee6342d4ad0b05ed53124/pilot/pkg/status/distribution/reporter.go#L117? Around how many istiod pods do you have?

**Comment by Laci21** [comment]
Hi @Obirah,

Yes, it was indeed an upstream bug: https://github.com/istio/istio/pull/41621

It is fixed in the latest upstream Istio patch versions `1.15.4` and `1.16.1`.

We'll need to adjust our operator for this change. Although this is not a big change, I cannot promise anything right now when this one will be fixed. Are you up for sending a PR maybe?

**Comment by Laci21** [comment]
Hi,

We fixed this in https://github.com/banzaicloud/istio-operator/pull/879 (in this commit exactly: https://github.com/banzaicloud/istio-operator/pull/879/commits/6cffcc2b723e96b454512e384ae6f5a71e87580d).

It'll be part of the latest Istio operator release with Istio 1.16.1 support (not released yet, will be released soon).

@Obirah, please let us know in case you'd need this fix for Istio 1.15.x versions as well.

**Comment by Laci21** [comment]
The release is available: https://github.com/banzaicloud/istio-operator/releases/tag/v2.16.0

Feel free to reopen in case you'd need this fix for Istio 1.15.x versions as well.
